"""Snowflake DDL generation and load instructions.

The pipeline does not connect to Snowflake. It emits DDL plus a documented
COPY INTO path from the Parquet output, so loading is an explicit, credentialed
step performed by whoever owns the warehouse -- not a side effect of building
the database.

Design notes for Snowflake specifically:

* Geometry is stored as WKT ``VARCHAR`` in the staging tables and converted to
  ``GEOGRAPHY`` in the analytic views. GEOGRAPHY uses spherical semantics,
  which is what a global storm-track dataset wants; GEOMETRY would apply
  planar maths to lon/lat degrees and give wrong distances.
* Clustering keys are chosen for the access patterns these tables actually
  see: season/basin scans on track_points, and season/state scans on
  landfalls.
* Booleans are real ``BOOLEAN``, not 0/1 integers, so filters read naturally.
"""

from __future__ import annotations

import logging
from pathlib import Path

log = logging.getLogger(__name__)

DDL_TEMPLATE = """\
-- =====================================================================
-- HUTrackDB - Snowflake schema
-- Generated by hutrackdb.db.snowflake; do not hand-edit.
--
-- Load path:
--   1. Upload data/processed/parquet/*.parquet to a stage
--   2. Run this DDL
--   3. Run the COPY INTO statements at the foot of this file
--   4. Create the GEOGRAPHY views
-- =====================================================================

CREATE DATABASE IF NOT EXISTS {database};
USE DATABASE {database};
CREATE SCHEMA IF NOT EXISTS {schema};
USE SCHEMA {schema};

-- ---------------------------------------------------------------------
-- storms : one row per cyclone (header-level)
-- ---------------------------------------------------------------------
CREATE OR REPLACE TABLE STORMS (
    STORM_ID                  VARCHAR(16)  NOT NULL PRIMARY KEY,
    BASIN                     VARCHAR(2)   NOT NULL,
    CYCLONE_NUMBER            NUMBER(3,0)  NOT NULL,
    SEASON                    NUMBER(4,0)  NOT NULL,
    NAME                      VARCHAR(64),
    N_TRACK_POINTS            NUMBER(6,0)  NOT NULL,
    N_TRACK_POINTS_DECLARED   NUMBER(6,0)  NOT NULL,
    START_TIME_UTC            TIMESTAMP_NTZ,
    END_TIME_UTC              TIMESTAMP_NTZ,
    PEAK_WIND_KT              NUMBER(4,0),
    MIN_PRESSURE_MB           NUMBER(5,0),
    PEAK_SS_CATEGORY          VARCHAR(4),
    IS_MAJOR_HURRICANE        BOOLEAN,
    MIN_DISTANCE_TO_COAST_KM  FLOAT,
    N_LANDFALLS               NUMBER(4,0)  NOT NULL DEFAULT 0,
    N_US_LANDFALLS            NUMBER(4,0)  NOT NULL DEFAULT 0,
    MADE_LANDFALL             BOOLEAN      NOT NULL DEFAULT FALSE,
    MADE_US_LANDFALL          BOOLEAN      NOT NULL DEFAULT FALSE,
    SOURCE_FILE               VARCHAR(256),
    TRACK_WKT                 VARCHAR       -- LINESTRING; see V_STORMS
)
CLUSTER BY (SEASON, BASIN)
COMMENT = 'HURDAT2 header-level cyclone records with lifetime summary attributes.';

-- ---------------------------------------------------------------------
-- track_points : long-form best-track observations, joinable to STORMS
-- ---------------------------------------------------------------------
CREATE OR REPLACE TABLE TRACK_POINTS (
    STORM_ID                  VARCHAR(16)  NOT NULL,
    POINT_SEQ                 NUMBER(6,0)  NOT NULL,
    TIMESTAMP_UTC             TIMESTAMP_NTZ NOT NULL,
    RECORD_IDENTIFIER         VARCHAR(1),
    STATUS                    VARCHAR(2)   NOT NULL,
    LATITUDE                  FLOAT        NOT NULL,
    LONGITUDE                 FLOAT        NOT NULL,
    MAX_WIND_KT               NUMBER(4,0),
    MIN_PRESSURE_MB           NUMBER(5,0),
    R34_NE_NM NUMBER(5,0), R34_SE_NM NUMBER(5,0),
    R34_SW_NM NUMBER(5,0), R34_NW_NM NUMBER(5,0),
    R50_NE_NM NUMBER(5,0), R50_SE_NM NUMBER(5,0),
    R50_SW_NM NUMBER(5,0), R50_NW_NM NUMBER(5,0),
    R64_NE_NM NUMBER(5,0), R64_SE_NM NUMBER(5,0),
    R64_SW_NM NUMBER(5,0), R64_NW_NM NUMBER(5,0),
    RADIUS_MAX_WIND_NM        NUMBER(5,0),
    IS_SYNOPTIC               BOOLEAN      NOT NULL,
    IS_NATIVE_LANDFALL_RECORD BOOLEAN      NOT NULL,
    SS_CATEGORY               VARCHAR(4),
    IS_MAJOR_HURRICANE        BOOLEAN,
    IS_OVER_LAND              BOOLEAN,
    MIN_DISTANCE_TO_COAST_KM  FLOAT,
    NEAREST_COAST_LON         FLOAT,
    NEAREST_COAST_LAT         FLOAT,
    BASIN                     VARCHAR(2),
    SEASON                    NUMBER(4,0),
    SOURCE_LINE_NO            NUMBER(9,0),
    CONSTRAINT PK_TRACK_POINTS PRIMARY KEY (STORM_ID, POINT_SEQ),
    CONSTRAINT FK_TRACK_STORM  FOREIGN KEY (STORM_ID) REFERENCES STORMS(STORM_ID)
)
CLUSTER BY (SEASON, BASIN, STORM_ID)
COMMENT = 'Long-form 6-hourly and asynoptic best-track records. MIN_DISTANCE_TO_COAST_KM is populated for every point.';

-- ---------------------------------------------------------------------
-- landfall_gates : swappable coastal reference set
-- ---------------------------------------------------------------------
CREATE OR REPLACE TABLE LANDFALL_GATES (
    GATE_ID     VARCHAR(64) NOT NULL PRIMARY KEY,
    GATE_NAME   VARCHAR(256),
    REGION      VARCHAR(128),
    SORT_ORDER  NUMBER(9,0),
    GATE_WKT    VARCHAR      -- LINESTRING crossing the shoreline
)
COMMENT = 'Coastal gate reference set. Replaceable with a proprietary set; see docs/GATES.md.';

-- ---------------------------------------------------------------------
-- landfalls : one row per coastline crossing (NOT one per storm)
-- ---------------------------------------------------------------------
CREATE OR REPLACE TABLE LANDFALLS (
    STORM_ID                   VARCHAR(16) NOT NULL,
    LANDFALL_SEQ               NUMBER(4,0) NOT NULL,
    LANDFALL_TYPE              VARCHAR(32) NOT NULL,
    DETECTION_METHOD           VARCHAR(24) NOT NULL,
    IS_LANDFALL                BOOLEAN     NOT NULL,
    EXACT_TIME                 TIMESTAMP_NTZ,
    EXACT_LAT                  FLOAT,
    EXACT_LON                  FLOAT,
    EXACT_WIND_KT              NUMBER(4,0),
    EXACT_PRESSURE_MB          NUMBER(5,0),
    EXACT_SS_CATEGORY          VARCHAR(4),
    EXACT_IS_OFFCADENCE        BOOLEAN,
    SIXHR_TIME                 TIMESTAMP_NTZ,
    SIXHR_LAT                  FLOAT,
    SIXHR_LON                  FLOAT,
    SIXHR_WIND_KT              NUMBER(4,0),
    SIXHR_PRESSURE_MB          NUMBER(5,0),
    SIXHR_SS_CATEGORY          VARCHAR(4),
    HOURS_FROM_6HR_TO_LANDFALL FLOAT,
    LANDFALL_ADMIN1            VARCHAR(128),
    LANDFALL_COUNTRY           VARCHAR(128),
    LANDFALL_ISO               VARCHAR(8),
    IS_US_LANDFALL             BOOLEAN,
    IS_MAINLAND_LANDFALL       BOOLEAN,
    LANDMASS_AREA_KM2          FLOAT,
    LANDMASS_ID                NUMBER(9,0),
    LANDFALL_ADMIN_DISTANCE_KM FLOAT,
    IS_ATTRIBUTION_EXACT       BOOLEAN,
    GATE_ID                    VARCHAR(64),
    GATE_REGION                VARCHAR(128),
    GATE_DISTANCE_KM           FLOAT,
    STATUS_AT_LANDFALL         VARCHAR(2),
    IS_TROPICAL_AT_LANDFALL    BOOLEAN,
    NATIVE_FLAGGING_COMPLETE   BOOLEAN,
    SOURCE_POINT_SEQ           NUMBER(6,0),
    CONSTRAINT FK_LANDFALL_STORM FOREIGN KEY (STORM_ID) REFERENCES STORMS(STORM_ID),
    CONSTRAINT FK_LANDFALL_GATE  FOREIGN KEY (GATE_ID)  REFERENCES LANDFALL_GATES(GATE_ID)
)
CLUSTER BY (LANDFALL_ISO, LANDFALL_ADMIN1)
COMMENT = 'One row per coastline crossing. Filter IS_LANDFALL = TRUE for countable landfalls; rows with IS_LANDFALL = FALSE are overland re-entries (bay/sound crossings).';

-- ---------------------------------------------------------------------
-- bypasses : closest approach for storms that never made landfall
-- ---------------------------------------------------------------------
CREATE OR REPLACE TABLE BYPASSES (
    STORM_ID                    VARCHAR(16) NOT NULL PRIMARY KEY,
    BYPASS_TIME_UTC             TIMESTAMP_NTZ,
    BYPASS_LAT                  FLOAT,
    BYPASS_LON                  FLOAT,
    BYPASS_DISTANCE_TO_COAST_KM FLOAT,
    BYPASS_NEAREST_COAST_LAT    FLOAT,
    BYPASS_NEAREST_COAST_LON    FLOAT,
    BYPASS_WIND_KT              NUMBER(4,0),
    BYPASS_PRESSURE_MB          NUMBER(5,0),
    BYPASS_SS_CATEGORY          VARCHAR(4),
    BYPASS_STATUS               VARCHAR(2),
    BYPASS_POINT_SEQ            NUMBER(6,0),
    BYPASS_RADIUS_KM_USED       FLOAT,
    CONSTRAINT FK_BYPASS_STORM FOREIGN KEY (STORM_ID) REFERENCES STORMS(STORM_ID)
)
COMMENT = 'Near-miss storms and their point of closest approach. The radius used is recorded per row; re-threshold from TRACK_POINTS.MIN_DISTANCE_TO_COAST_KM for any other cutoff.';

CREATE OR REPLACE TABLE PIPELINE_METADATA (
    KEY   VARCHAR(128) NOT NULL PRIMARY KEY,
    VALUE VARCHAR
)
COMMENT = 'Build provenance: source files and checksums, coastline, gate set, and every calibration value with its status and source.';

-- =====================================================================
-- GEOGRAPHY views
-- WKT is converted here rather than stored as GEOGRAPHY directly, so the
-- COPY INTO stays a plain columnar load and the spatial types are derived.
-- =====================================================================

CREATE OR REPLACE VIEW V_TRACK_POINTS AS
SELECT t.*,
       ST_MAKEPOINT(t.LONGITUDE, t.LATITUDE)                     AS GEOG,
       ST_MAKEPOINT(t.NEAREST_COAST_LON, t.NEAREST_COAST_LAT)    AS NEAREST_COAST_GEOG
FROM TRACK_POINTS t;

CREATE OR REPLACE VIEW V_LANDFALLS AS
SELECT l.*,
       ST_MAKEPOINT(l.EXACT_LON, l.EXACT_LAT) AS GEOG,
       ST_MAKEPOINT(l.SIXHR_LON, l.SIXHR_LAT) AS SIXHR_GEOG
FROM LANDFALLS l;

CREATE OR REPLACE VIEW V_STORMS AS
SELECT s.*,
       TRY_TO_GEOGRAPHY(s.TRACK_WKT) AS TRACK_GEOG
FROM STORMS s;

CREATE OR REPLACE VIEW V_LANDFALL_GATES AS
SELECT g.*,
       TRY_TO_GEOGRAPHY(g.GATE_WKT) AS GATE_GEOG
FROM LANDFALL_GATES g;

-- Convenience view: countable US landfalls only.
CREATE OR REPLACE VIEW V_US_LANDFALLS AS
SELECT l.*, s.NAME, s.SEASON, s.BASIN
FROM LANDFALLS l
JOIN STORMS s ON s.STORM_ID = l.STORM_ID
WHERE l.IS_LANDFALL = TRUE
  AND l.IS_US_LANDFALL = TRUE;

-- =====================================================================
-- COPY INTO  (adjust the stage name to your environment)
-- =====================================================================
-- CREATE OR REPLACE FILE FORMAT PARQUET_FMT TYPE = PARQUET;
-- CREATE OR REPLACE STAGE HUTRACKDB_STAGE FILE_FORMAT = PARQUET_FMT;
-- PUT file://data/processed/parquet/*.parquet @HUTRACKDB_STAGE;
--
-- COPY INTO STORMS          FROM @HUTRACKDB_STAGE/storms.parquet
--   MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = PARQUET_FMT;
-- COPY INTO TRACK_POINTS    FROM @HUTRACKDB_STAGE/track_points.parquet
--   MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = PARQUET_FMT;
-- COPY INTO LANDFALL_GATES  FROM @HUTRACKDB_STAGE/landfall_gates.parquet
--   MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = PARQUET_FMT;
-- COPY INTO LANDFALLS       FROM @HUTRACKDB_STAGE/landfalls.parquet
--   MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = PARQUET_FMT;
-- COPY INTO BYPASSES        FROM @HUTRACKDB_STAGE/bypasses.parquet
--   MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = PARQUET_FMT;
-- COPY INTO PIPELINE_METADATA FROM @HUTRACKDB_STAGE/pipeline_metadata.parquet
--   MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE FILE_FORMAT = PARQUET_FMT;
"""


def write_snowflake_ddl(config, path: Path | None = None) -> Path:
    """Render the Snowflake DDL for the configured database and schema."""
    database = config.get("output.snowflake_database", "HUTRACKDB")
    schema = config.get("output.snowflake_schema", "PUBLIC")
    target = path or (
        config.output_dir() / config.get("output.snowflake_ddl", "snowflake_ddl.sql")
    )
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(DDL_TEMPLATE.format(database=database, schema=schema))
    log.info("wrote Snowflake DDL %s", target)
    return target
